### ISSUE TITLE
What is the status? 

### ISSUE THREAD

**Issue by b-sh** [TriDis/llvm-tricore#1]
Hi @sidneyp,

I am just curios about the status and how is this related to the thesis of Christoph Erhardt https://opus4.kobv.de/opus4-fau/frontdoor/index/index/docId/1108? 

Thank you for feedback in advance.

**Comment by sidneyp** [comment]
Hello @b-sh,

The status is that the code is working, but partially. What I remember is that the major instructions are implemented.
The thesis of Christoph Erhardt is a reference for this work together with the TriCore manual docs.

Thank you too!

**Comment by b-sh** [comment]
ok I will check.

**Comment by b-sh** [comment]
OK I have synced on llvm release/13.x branch https://github.com/b-sh/llvm-project/tree/bsh/tricore to experiment using it as backend in rust https://github.com/b-sh/ruos as a first step.

**Comment by sidneyp** [comment]
How was it? Did it work?

**Comment by b-sh** [comment]
> How was it? Did it work?

Yes, but there are still some gaps in migration. I had also to fix AsmPrinter. I need to walk through the full code. I have seen that https://github.com/kumailxp/tricore_llvm/tree/master/Tests has some Tests so probably I will check the correctness of latest migration. Overall the API of LLVM is quite stable and very nice and got stronger on Types. The latest issue I have is at the moment something in DAG when compiling rust core. I have not properly migrated to the new way of handling the SDNodes. Let´s see.
