### ISSUE TITLE
Similar to ditricore but can you demonstrate how to build this version?

### ISSUE THREAD

**Issue by DarrylC03** [TriDis/llvm-tricore#2]
Would it be possible to show how to build this version of llvm-tricore? I am interested in the Capstone tricore disassembler as well as ditricore but I am having difficulty building this component. 

Thanks in Advance.

Regards, Darryl

**Comment by sidneyp** [comment]
Hello, Darryl! It is great you are interested on it! I do not work on these two projects since 2016. However, I have the building commands for them. Here is for the llvm-tricore:

```
mkdir build-llvm-tricore
cd build-llvm-tricore

cmake ../llvm-tricore

cmake ../llvm-tricore -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5

cmake --build .

cmake --build . --target install

cmake -DCMAKE_INSTALL_PREFIX=/tmp/llvm -P cmake_install.cmake
-DCMAKE_EXECUTABLE_SUFFIX=<suffix>
```

**Comment by DarrylC03** [comment]
Thank you. I tried building it in cygwin.

I do not have gcc-5 nor g++-5 installed so I just used the defaults gcc/g++ and I got up to:

    cmake --build . 

and it fails with the following:

![image](https://user-images.githubusercontent.com/25788376/88290675-7b616880-cd3a-11ea-8bfa-85272e8b7be0.png)

Which would imply the build scripts seem to be not generating the rules properly as it looks like a normal g++ would build this file. Perhaps it is Cygwin so could you detail what platform you built this on, that would be very helpful.

Thanks in advance.

**Comment by sidneyp** [comment]
Yes, sure! I built it in a virtual machine with Ubuntu probably version 12.04 or 14.04. I think I installed a different gcc version to be able to build the original llvm and llvm-tricore. I think you can install gcc-5 with:
```
sudo apt install g++-5
sudo apt install gcc-5
```
